---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jenkins App
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: jenkinsdind
          namespace: dev-tools
        spec:
          selector:
            matchLabels:
              app: jenkinsdind
          replicas: 1
          template:
            metadata:
              labels:
                app: jenkinsdind
              name: jenkinsdind
            spec:
              hostNetwork: true
              containers:
                - name: jenkinsdind
                  image: vixns/jenkins-dind:latest
                  securityContext:
                    privileged: true
                    fsGroup: 1000 
                    runAsUser: 0
                  resources:
                    requests:
                      memory: "3G"
                  volumeMounts:
                    - name: jenkins-dind-pv-volume
                      mountPath: /var/jenkins_home
                  ports:
                    - name: http-port
                      containerPort: 8080
                    - name: jnlp-port
                      containerPort: 50000
                  dnsPolicy: "ClusterFirst"
              volumes:
                - name: jenkins-dind-pv-volume
                  persistentVolumeClaim:
                    claimName: jenkins-dind-pv-claim
